version: 2
updates:
  - package-ecosystem: "pip"
    directory: "{{cookiecutter.package_name}}"
    schedule:
      interval: "daily"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
